# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 957438016edde7dac412aa877e330474edae2298428de23ba3f1c92c820fbde297f284d1dab7af1599aec9312ce60403bd4e83817f56fa2b7c98c2fa2f69d7ee

test:
  secret_key_base: a135d651a512addad664bb26e41dc14937c79f166f952b6d301b1ec8ed33845b6e14d7d2b11dbae076cb2907aad993c6da1ca4037982d31aed82ef11f66f131d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
